---
abstract: 'Object for running system commands'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Command
provides:
  System::Command:
    file: lib/System/Command.pm
    version: 1.00
  System::Command::Reaper:
    file: lib/System/Command/Reaper.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
