---
abstract: 'Object for running system commands'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Command
provides:
  System::Command:
    file: lib/System/Command.pm
    version: 1.09
requires:
  Carp: 0
  Config: 0
  Cwd: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  POSIX: 0
  Symbol: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/System-Command
version: 1.09
